### ISSUE TITLE
[WISE Bug]: Build Fails compiling protobuf in FBP

### ISSUE THREAD

**Issue by spydmobile** [WISE-Developers/WISE_Application#53]
### Contact Details

spydmobile@gmail.com

### What happened?

The bad news is that after updating the expired personal access token for the automated build process, WISE is having problems compiling protobuf in FBP and so the build is failing

![image](https://github.com/WISE-Developers/WISE_Application/assets/1065978/3c410d28-1d36-4614-baf4-67ccfb685a7f)

![image](https://github.com/WISE-Developers/WISE_Application/assets/1065978/d02e45f2-89ba-4dba-aa10-c0b2f452d20a)

### Version

(Ubuntu 2022) v1.0.0-beta

### What component are you seeing the problem on?

Other (indicate in "What happened" above)

### Relevant log output

```shell
see:
https://github.com/WISE-Developers/WISE_Application/actions/runs/8214421182/job/22466899027
```

### Approvals Process

- [ ] Testing For Issue
- [ ] Executive Approval
- [ ] Merge

**Comment by spydmobile** [comment]
@RobBryce @tredpath double check this is not simply your PAT for HSS expired.

**Comment by spydmobile** [comment]
@tredpath @RobBryce 
ok, now the problems have moved up the list:
https://github.com/WISE-Developers/WISE_Application/actions/runs/8298852792/job/22713190655#step:86:150

fixing this issue like this will take forever.

I am authorizing HSS to go ahead and merge your own PRs to fix this issue, once you have this building we can go back authorizing your PRs please.

**Comment by tredpath** [comment]
The build runs now. I had to downgrade the Paho C++ version to 1.2.0 (really it's the same version that WISE was released with previously). This is further back than I wanted to go, I had hoped going to 1.3.2 would be enough as it removes eclipse/paho.mqtt.cpp#374 which breaks the build here but there were further issues on Windows caused by the changes to message.h in [this commit](https://github.com/eclipse/paho.mqtt.cpp/commit/ab98b289b68e41f3ff53c119515a271fc7b43ab2).

@spydmobile, do you know what permissions the PAT you used when updating the WISE_PAT variable had? The release stage isn't able to push tags to other projects. If it is a permissions issue the [release stage of the last action run](https://github.com/WISE-Developers/WISE_Application/actions/runs/8302194438/job/22724754462) should be able to be rerun without redoing the entire build after it's fixed.

**Comment by tredpath** [comment]
Also, I updated the version to 1.0.6-beta.6 which hopefully works as a release version.

**Comment by spydmobile** [comment]
i have tried everything, i cant fix this. I have opened a ticket with Github.

https://support.github.com/ticket/personal/0/2678132

**Comment by spydmobile** [comment]
ok @tredpath @ @RobBryce , heard back from github, this is because of new stricter PAT policies, I made a CLASSIC token instead with full powers and no expire and made that the new WISE_PAT in Wise application, and reran the release and it went, closing this.
